package config

// noinspection ALL
const (
	ENV             = "ENV"
	ENV_DEVELOPMENT = "development"
	ENV_MOCK        = "mock"
	ENV_PRODUCTION  = "production"
)

// noinspection ALL
const (
	HTTP_ADDRESS = "HTTP_ADDRESS"

	DATABASE_CONNECTION_STRING = "DATABASE_CONNECTION_STRING"

	DATABASE_DRIVER = "DATABASE_DRIVER"
	DATABASE_HOST   = "DATABASE_HOST"
	DATABASE_PORT   = "DATABASE_PORT"
	DATABASE_USER   = "DATABASE_USER"
	DATABASE_PASS   = "DATABASE_PASS"
	DATABASE_NAME   = "DATABASE_NAME"
)
